### ISSUE TITLE
Perdida de información al momento de actualizar

### ISSUE THREAD

**Issue by ealejandro101** [davidherney/moodle-format_menutopic#12]
David, 

Luego de actualizar el pluguin se pierde la configuración y datos propios del pluguin para el curso.

Estas son algunas imágenes que tenemos.

 **Configuración del curso luego de la actualización, se perdio la configuración en el curso.**
![image](https://user-images.githubusercontent.com/28930441/35455675-d98794aa-02a0-11e8-8a97-81ab0cdd0001.png)

**Arbol del menu antes de la actualización del pluguin**

![image](https://user-images.githubusercontent.com/28930441/35455522-357c57ce-02a0-11e8-8d3b-746753d39381.png)

**Arbol del menu luego de la actualización del pluguin**

![image](https://user-images.githubusercontent.com/28930441/35455628-afa24d38-02a0-11e8-9386-77a7554ef6a1.png)

**Comment by davidherney** [comment]
Hola Alejandro...

¿desde qué versión actualizaste y a qué versión? ¿por qué estaba el curso en "formato semanal" antes de actualizar?

Saludos
