### ISSUE TITLE
Excepción - Call to a member function notification() on null

### ISSUE THREAD

**Issue by univirtualutp** [davidherney/moodle-format_menutopic#17]
Hello, I'm having this issue after updating the plugin on my site.

The Notice appears when I try to edit a course menu.

this is the complete log debug

Notice: Undefined variable: OUTPUT in /var/www/aulavirtual/course/format/menutopic/form_tree.php on line 107

Excepción - Call to a member function notification() on null

×Debug info:

Error code: generalexceptionmessage

×Stack trace:

line 107 of /course/format/menutopic/form_tree.php: Error thrown

line 415 of /course/format/menutopic/renderer.php: call to include()

line 71 of /course/format/menutopic/format.php: call to format_menutopic_renderer->print_edition_page()

line 290 of /course/view.php: call to require()

Thank you for your help.

**Comment by univirtualutp** [comment]
Perdón por escribir en ingles, 

Después de actualizar todos los plugins en nuestro moodle, este error empezó a aparecer cuando se va a editar el menú en cualquier curso.

Agradezco mucho tu colaboración, feliz día.

**Comment by davidherney** [comment]
Hola @univirtualutp ¿en qué versión lo probaste? Porque ese error se corrigió en la última liberación.

Saludos

**Comment by univirtualutp** [comment]
Hola @davidherney estoy usando moodle 3.7 y la versión que aparece es 2020052901
gracias por tu pronta respuesta.

**Comment by davidherney** [comment]
Yo no monté las correcciones en todas las versiones anteriores, creería que en esa todavía no la había montado. Te recomiendo que mires los cambios de este commit y los apliques. Son muy simples y sería muy rápido de ajustar localmente:
https://github.com/davidherney/moodle-format_menutopic/commit/ab5011e23e8674d979e35df6945ab5db62eb15bd

Saludos

**Comment by univirtualutp** [comment]
Finalmente hice los cambios en los archivos, pero intente actualizar el moodle a 3.10 y el plugin menutopic no quedó en el nuevo moodle, quisiera saber que se debe hacer, si se debe pasar directamente la carpeta o si al instalarlo en el moodle 3.10 no se va a perder la información que ya se está usando con "menutopic" en los cursos.
