### ISSUE TITLE
Problema com as camadas

### ISSUE THREAD

**Issue by GuiSchenkel** [davidherney/moodle-format_menutopic#19]
Bom dia, estou dendo dificuldade no processo de colocar 3 camadas em tópicos, na segunda camada ela fica desconfigurada

![erro](https://user-images.githubusercontent.com/102038234/159268558-44aa0eb4-d831-491b-a272-58e7025e9ea8.png)

**Comment by davidherney** [comment]
En las pruebas que hice siempre funcionó bien, quizá sea por los últimos cambios que se han realizado. Por ahorra cierro este reporte pero por favor abrirlo de nuevo si se vuelve a detectar.
![manue_tresniveles](https://github.com/davidherney/moodle-format_menutopic/assets/6455806/b3f2dbbf-f36c-4d6b-821b-37999d2e73eb)
