### ISSUE TITLE
Menu tree issue in Moodle 2.9?

### ISSUE THREAD

**Issue by rdeber** [davidherney/moodle-format_menutopic#3]
Hello, we are seeing a problem in Moodle 2.9 with menutopic when we try to edit the _menu tree_. When we click on the menu tree tab the tree structure section below is empty. It seems like the menu is failing to load on the page. There's also this javascript error: 

_lib.js:12 Uncaught TypeError: Cannot read property 'appendChild' of undefined_

Everything works fine when we tested in Moodle 3.0, so the problem seemed limited to m2.9. See the image attachment for more details.

![menutopic-moodle29-error](https://cloud.githubusercontent.com/assets/20683148/17176724/0341e96e-53dc-11e6-950c-29cabd4fc876.jpg)

Thank you.

**Comment by davidherney** [comment]
Hi...

I think that the error is in the json structure of the tree. Can you send me the hidden textarea 'treecode' content? In order to check it. Maybe the code was wrong saved in some operation.

Saludos

**Comment by rdeber** [comment]
Here's the HTML for the hidden textarea:

`<textarea style="display:none;" name="treecode" id="id_treecode">{"topics": [{"name" : "Topic 0",         "subtopics": [],         "topicnumber": 0,         "url": "",         "target": ""},
{"name" : "Topic 1",         "subtopics": [],         "topicnumber": 1,         "url": "",         "target": ""},
{"name" : "Topic 2",         "subtopics": [],         "topicnumber": 2,         "url": "",         "target": ""},
{"name" : "Topic 3",         "subtopics": [],         "topicnumber": 3,         "url": "",         "target": ""},
{"name" : "Topic 4",         "subtopics": [],         "topicnumber": 4,         "url": "",         "target": ""},
{"name" : "Topic 5",         "subtopics": [],         "topicnumber": 5,         "url": "",         "target": ""},
{"name" : "Topic 6",         "subtopics": [],         "topicnumber": 6,         "url": "",         "target": ""},
{"name" : "Topic 7",         "subtopics": [],         "topicnumber": 7,         "url": "",         "target": ""},
{"name" : "Topic 8",         "subtopics": [],         "topicnumber": 8,         "url": "",         "target": ""},
{"name" : "Topic 9",         "subtopics": [],         "topicnumber": 9,         "url": "",         "target": ""},
{"name" : "Topic 10",         "subtopics": [],         "topicnumber": 10,         "url": "",         "target": ""}]}</textarea>`

Thanks for your help.

**Comment by davidherney** [comment]
Hi...

I test it and the tree structure is right and It worked fine in moodle 2.9.
Maybe, you install the incorrect format version in your moodle. I don't found other explanation. Can you send me a teacher account? in order to test it directly in your platform.

Saludos
