### ISSUE TITLE
Database Error when creating questions for quizzes

### ISSUE THREAD

**Issue by astoeffer** [davidherney/moodle-format_menutopic#4]
HI,

attached you find a screenshot with the debug message for the issue in the subject.
Moodle Version is 3.1.2 latest.

Thanks
Andreas
<img width="1188" alt="db_fehler-menutopic" src="https://cloud.githubusercontent.com/assets/7913176/18633012/8a4d86e8-7e7a-11e6-9550-f14f8866537f.png">

**Comment by davidherney** [comment]
Fixed!!!

Please test and comment.

Saludos
